### ISSUE TITLE
Windows development env

### ISSUE THREAD

**Issue by bruderstein** [bruderstein/npppm3#17]
Docker isn't too easy on windows (or has requirements for specific versions)

Removing this requirement for Windows development will involve adding some options to the startup script to detect windows and optionally not start the CouchDB container, but rely on it being installed and available.

Some further setup instructions will also be needed.

**Comment by chcg** [comment]
Current output on calling yarn install:

> yarn install v0.21.3
warning npppm@3.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "react-tooltip@3.2.6" has unmet peer dependency "react@^0.14.0 || ^15.0.0".
warning "react-tooltip@3.2.6" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0".
[4/4] Building fresh packages...
[1/3] ⠈ bcrypt: gyp info using node@7.7.2 | win32 | x64
[-/3] ⠈ waiting...
[3/3] ⠈ dtrace-provider
[-/3] ⠈ waiting...
error C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt: Command failed.
Exit code: 1
Command: C:\WINDOWS\system32\cmd.exe
Arguments: /d /s /c node-pre-gyp install --fallback-to-build
Directory: C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.30
node-pre-gyp info using node@7.7.2 | win32 | x64
node-pre-gyp info check checked for "C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt\lib\binding\bcrypt_lib.node" (not found)
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.1/bcrypt_lib-v1.0.1-node-v51-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.1/bcrypt_lib-v1.0.1-node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download: https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.1/bcrypt_lib-v1.0.1-node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.1 and node@7.7.2 (node-v51 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http Pre-built binary not available for your system, looked for https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.1/bcrypt_lib-v1.0.1-node-v51-win32-x64.tar.gz

C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\Yarn\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.7.2 | win32 | x64
gyp info ok

C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\Yarn\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt\lib\binding )  else (node  configure --fallback-to-build --module=C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt\lib\binding )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.7.2 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files (x86)\Yarn\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files (x86)\Yarn\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Program Files (x86)\Yarn\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:114:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\christian\\Source\\Repos\\nppPluginManagerServer\\npppm3\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=C:\\Users\\christian\\Source\\Repos\\nppPluginManagerServer\\npppm3\\node_modules\\bcrypt\\lib\\binding"
gyp ERR! cwd C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt\lib\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\christian\\Source\\Repos\\nppPluginManagerServer\\npppm3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt
node-pre-gyp ERR! node -v v7.7.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\node_modules\bcrypt\lib\binding' (1)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**Comment by chcg** [comment]
npm start of just the client has this errors:

```
ERROR in ./src/components/PluginEditor/NewPlugin.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../../actions in C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\client\src\components\PluginEditor
 @ ./src/components/PluginEditor/NewPlugin.jsx 15:15-39

ERROR in ./src/components/PluginEditor/PluginEditor.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../../actions in C:\Users\christian\Source\Repos\nppPluginManagerServer\npppm3\client\src\components\PluginEditor
 @ ./src/components/PluginEditor/PluginEditor.jsx 23:15-39
```
